---
name: simple-assignment
break: true
fastfail: false
indent: 2
version: v1.1.0
---
./build.gradle:
  --description "Make a build.gradle file" ConfirmFileExists

--description "Have at least 4 commits" CountCommits --count 4

(pure) echo "check!"
